import mongoose from "mongoose";
import dotenv from "dotenv";
import connectDB from "./src/config/db.mjs";
import Product from "./src/models/product.mjs";
import Category from "./src/models/categories.mjs";

dotenv.config();

const frontendProducts = [
    {
        id: "pr1",
        name: "Grain-Free Salmon Adult Formula",
        brand: "Wildroot",
        price: 58,
        subPrice: 49,
        rating: 4.8,
        reviews: 312,
        image: "https://images.unsplash.com/photo-1725696866074-3a7f63fe004d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Grain-Free", "Omega-3", "Large Breed"],
        petType: "Dog",
        category: "Food",
        ageGroup: "Adult",
        size: "Large",
        description: "A nutrient-dense salmon recipe crafted for active adult dogs. High-quality protein, rich omega fats, and zero filler grains.",
    },
    {
        id: "pr2",
        name: "Indoor Cat Chicken Dinner",
        brand: "Whiskerly",
        price: 34,
        subPrice: 29,
        rating: 4.7,
        reviews: 189,
        image: "https://images.unsplash.com/photo-1736367536182-51ffce2eee0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Hairball Care", "Indoor", "Real Chicken"],
        petType: "Cat",
        category: "Food",
        ageGroup: "Adult",
        size: "Medium",
        description: "Complete daily nutrition for indoor adult cats. Supports healthy digestion with prebiotic fiber and natural hairball control.",
    },
    {
        id: "pr3",
        name: "Plush Lamb Comfort Toy",
        brand: "Pawnest",
        price: 18,
        subPrice: 16,
        rating: 4.9,
        reviews: 521,
        image: "https://images.unsplash.com/photo-1764936510280-5be0d339dda6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Soft", "Squeaker", "Small Breeds"],
        petType: "Dog",
        category: "Toys",
        ageGroup: "Puppy",
        size: "Small",
        description: "A soft, cuddly lamb companion with a gentle squeaker — perfect for puppies and small-breed snugglers.",
    },
    {
        id: "pr4",
        name: "Puppy Growth Chicken & Duck",
        brand: "Wildroot",
        price: 46,
        subPrice: 39,
        rating: 4.6,
        reviews: 143,
        image: "https://images.unsplash.com/photo-1684882726821-2999db517441?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Puppy", "DHA", "Joint Support"],
        petType: "Dog",
        category: "Food",
        ageGroup: "Puppy",
        size: "All",
        description: "A premium puppy recipe with DHA for brain development and balanced minerals for growing bones.",
    },
    {
        id: "pr5",
        name: "Fetch Pro Rubber Frisbee",
        brand: "Pawnest",
        price: 22,
        subPrice: 20,
        rating: 4.5,
        reviews: 97,
        image: "https://images.unsplash.com/photo-1678652231344-109ed2855ea9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Durable", "Floats", "Outdoor"],
        petType: "Dog",
        category: "Toys",
        ageGroup: "Adult",
        size: "Medium",
        description: "Tough natural rubber frisbee designed for long fetch sessions. Floats, flies straight, and gentle on teeth.",
    },
    {
        id: "pr6",
        name: "Daily Joint Support Chews",
        brand: "Vetbloom",
        price: 32,
        subPrice: 27,
        rating: 4.8,
        reviews: 276,
        image: "https://images.unsplash.com/photo-1645649835084-dc1d1eb24b49?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Glucosamine", "Senior", "Vet Formulated"],
        petType: "Dog",
        category: "Health",
        ageGroup: "Senior",
        size: "All",
        description: "Soft chews with glucosamine, chondroitin, and turmeric to support joint mobility in adult and senior dogs.",
    },
    {
        id: "pr7",
        name: "Pure Oat Calming Shampoo",
        brand: "Pawnest",
        price: 24,
        subPrice: 21,
        rating: 4.7,
        reviews: 210,
        image: "https://images.unsplash.com/photo-1647616350787-6428e907a7fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Sensitive Skin", "Natural", "pH-Balanced"],
        petType: "All",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "Gentle oat and aloe shampoo formulated for sensitive skin. Leaves coats soft, shiny, and beautifully clean.",
    },
    {
        id: "pr8",
        name: "Senior Cat Kidney Care",
        brand: "Whiskerly",
        price: 38,
        subPrice: 33,
        rating: 4.6,
        reviews: 88,
        image: "https://images.unsplash.com/photo-1623420797910-c7c3498d74fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Senior", "Kidney Health", "Low Phosphorus"],
        petType: "Cat",
        category: "Health",
        ageGroup: "Senior",
        size: "Medium",
        description: "Vet-formulated senior cat food with controlled phosphorus and antioxidants for long-term kidney wellness.",
    },
    {
        id: "pr9",
        name: "Interactive Laser Pointer",
        brand: "Pawnest",
        price: 15,
        subPrice: 12,
        rating: 4.4,
        reviews: 85,
        image: "https://images.unsplash.com/photo-1548366086-7f1b76106622?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Laser", "Exercise", "Interactive"],
        petType: "Cat",
        category: "Toys",
        ageGroup: "All",
        size: "All",
        description: "Keep your feline entertained for hours with this interactive laser pointer. Great for indoor exercise.",
    },
    {
        id: "pr10",
        name: "Dental Hygiene Chews",
        brand: "Vetbloom",
        price: 25,
        subPrice: 20,
        rating: 4.8,
        reviews: 420,
        image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Dental", "Plaque Control", "Fresh Breath"],
        petType: "Dog",
        category: "Health",
        ageGroup: "Adult",
        size: "Medium",
        description: "Daily dental chews that reduce tartar and freshen breath while offering a satisfying chew.",
    },
    {
        id: "pr11",
        name: "Tuna Flakes Treat",
        brand: "Whiskerly",
        price: 12,
        subPrice: 10,
        rating: 4.9,
        reviews: 650,
        image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Treat", "Tuna", "Natural"],
        petType: "Cat",
        category: "Food",
        ageGroup: "All",
        size: "All",
        description: "100% natural dried tuna flakes. Irresistible aroma and taste for kittens and adult cats alike.",
    },
    {
        id: "pr12",
        name: "Ergonomic Pet Brush",
        brand: "Pawnest",
        price: 19,
        subPrice: 15,
        rating: 4.6,
        reviews: 210,
        image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Grooming", "De-shedding", "Ergonomic"],
        petType: "All",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "Comfortable ergonomic grip brush that gently removes loose hair and reduces shedding up to 90%.",
    },
    {
        id: "pr13",
        name: "Catnip Mouse Toy",
        brand: "Whiskerly",
        price: 8,
        subPrice: 6,
        rating: 4.5,
        reviews: 130,
        image: "https://images.unsplash.com/photo-1563280053-5d3c8c7921a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Catnip", "Stuffed Toy", "Indoor"],
        petType: "Cat",
        category: "Toys",
        ageGroup: "All",
        size: "Small",
        description: "Filled with premium organic catnip, this mouse toy satisfies your cat's natural hunting instincts.",
    },
    {
        id: "pr14",
        name: "Odor Eliminating Spray",
        brand: "Pawnest",
        price: 14,
        subPrice: 11,
        rating: 4.4,
        reviews: 80,
        image: "https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Cleaning", "Odor", "Home"],
        petType: "All",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "Enzyme-based odor eliminator spray that tackles tough pet stains and neutralizes unpleasant smells instantly.",
    },
    {
        id: "pr15",
        name: "Squeaky Tennis Balls 3-Pack",
        brand: "Pawnest",
        price: 15,
        subPrice: 12,
        rating: 4.7,
        reviews: 310,
        image: "https://images.unsplash.com/photo-1544568100-847a948585b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Tennis Balls", "Squeaky", "Outdoor"],
        petType: "Dog",
        category: "Toys",
        ageGroup: "All",
        size: "Medium",
        description: "A classic favorite with a twist! Three highly visible squeaky tennis balls perfect for engaging games of fetch.",
    },
    {
        id: "pr16",
        name: "Premium Flea & Tick Drops (Dog)",
        brand: "Vetbloom",
        price: 45,
        subPrice: 40,
        rating: 4.8,
        reviews: 190,
        image: "https://images.unsplash.com/photo-1588691060932-d1cc87ef2ff4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Flea", "Tick", "Preventative"],
        petType: "Dog",
        category: "Health",
        ageGroup: "Adult",
        size: "Large",
        description: "Long-lasting topical drops that kill fleas and ticks on contact. Provides a full month of protection.",
    },
    {
        id: "pr17",
        name: "Premium Flea & Tick Drops (Cat)",
        brand: "Vetbloom",
        price: 42,
        subPrice: 38,
        rating: 4.7,
        reviews: 140,
        image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Flea", "Tick", "Preventative"],
        petType: "Cat",
        category: "Health",
        ageGroup: "Adult",
        size: "All",
        description: "Effective and safe flea & tick topical drops formulated specifically for cats. 30 days of reliable protection.",
    },
    {
        id: "pr18",
        name: "Wet Cat Food Variety Pack",
        brand: "Whiskerly",
        price: 28,
        subPrice: 24,
        rating: 4.8,
        reviews: 412,
        image: "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Wet Food", "Pate", "Variety"],
        petType: "Cat",
        category: "Food",
        ageGroup: "Adult",
        size: "All",
        description: "A 12-pack of savory pate wet food featuring chicken, salmon, and turkey flavors to satisfy picky eaters.",
    },
    {
        id: "pr19",
        name: "High-Protein Beef Kibble",
        brand: "Wildroot",
        price: 65,
        subPrice: 55,
        rating: 4.9,
        reviews: 240,
        image: "https://images.unsplash.com/photo-1585620385456-4759f3d5395a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["High-Protein", "Beef", "Kibble"],
        petType: "Dog",
        category: "Food",
        ageGroup: "Adult",
        size: "Large",
        description: "A powerhouse of nutrition with real beef as the first ingredient. formulated to maintain strong muscles for active dogs.",
    },
    {
        id: "pr20",
        name: "Nail Clipper with Safety Guard",
        brand: "Pawnest",
        price: 16,
        subPrice: 12,
        rating: 4.5,
        reviews: 180,
        image: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Nail Clipper", "Safety", "Stainless Steel"],
        petType: "All",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "Professional stainless steel clippers featuring a safety guard to prevent over-cutting. Suitable for dogs and cats.",
    },
    {
        id: "pr21",
        name: "Slow Feeder Puzzle Bowl",
        brand: "Pawnest",
        price: 26,
        subPrice: 22,
        rating: 4.6,
        reviews: 95,
        image: "https://images.unsplash.com/photo-1585846416120-3a737dad57b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Bowl", "Puzzle", "Slow Feeder"],
        petType: "Dog",
        category: "Toys",
        ageGroup: "All",
        size: "Medium",
        description: "Slows down gulpers by turning mealtime into a challenging and rewarding puzzle. Promotes healthy digestion.",
    },
    {
        id: "pr22",
        name: "Scratching Post Lounge",
        brand: "Whiskerly",
        price: 40,
        subPrice: 35,
        rating: 4.7,
        reviews: 205,
        image: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Scratching", "Lounge", "Furniture"],
        petType: "Cat",
        category: "Toys",
        ageGroup: "All",
        size: "Large",
        description: "A stylish multi-surface scratching lounge that saves your furniture while offering a cozy resting spot.",
    },
    {
        id: "pr23",
        name: "Hypoallergenic Dog Shampoo",
        brand: "Vetbloom",
        price: 22,
        subPrice: 18,
        rating: 4.8,
        reviews: 125,
        image: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Hypoallergenic", "Shampoo", "Sensitive"],
        petType: "Dog",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "Tear-free hypoallergenic shampoo tailored for puppies and dogs with allergy-prone skin.",
    },
    {
        id: "pr24",
        name: "Calming Pheromone Diffuser",
        brand: "Vetbloom",
        price: 35,
        subPrice: 30,
        rating: 4.5,
        reviews: 260,
        image: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Calming", "Pheromones", "Diffuser"],
        petType: "Cat",
        category: "Health",
        ageGroup: "All",
        size: "All",
        description: "Mimics natural feline comforting pheromones to reduce stress behaviors like scratching and hiding at home.",
    },
    {
        id: "pr25",
        name: "Waterless Bath Mousse",
        brand: "Pawnest",
        price: 18,
        subPrice: 15,
        rating: 4.4,
        reviews: 112,
        image: "https://images.unsplash.com/photo-1577905898394-0610363eb27e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Waterless", "Mousse", "Cat Grooming"],
        petType: "Cat",
        category: "Grooming",
        ageGroup: "All",
        size: "All",
        description: "No-rinse grooming mousse perfect for sensitive cats. Leaves coat shiny and smelling fresh without the trauma of a bath.",
    },
    {
        id: "pr26",
        name: "Beef Liver Training Treats",
        brand: "Wildroot",
        price: 16,
        subPrice: 13,
        rating: 4.9,
        reviews: 580,
        image: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Training", "Beef Liver", "Treats"],
        petType: "Dog",
        category: "Food",
        ageGroup: "All",
        size: "All",
        description: "Freeze-dried 100% beef liver treats. The perfect high-value reward for training puppies and dogs of all sizes.",
    },
    {
        id: "pr27",
        name: "Hairball Remedy Paste",
        brand: "Whiskerly",
        price: 14,
        subPrice: 11,
        rating: 4.6,
        reviews: 142,
        image: "https://images.unsplash.com/photo-1629835824901-447551065f3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=900&q=80",
        tags: ["Hairball", "Remedy", "Paste"],
        petType: "Cat",
        category: "Health",
        ageGroup: "Adult",
        size: "All",
        description: "Tasty salmon-flavored paste that lubricates hair safely through the digestive tract. Helps prevent hairballs.",
    }
];

const seedDB = async () => {
    try {
        await connectDB();

        // Ensure Categories exist
        const uniqueCategories = [...new Set(frontendProducts.map(p => p.category))];
        const categoryMap = {};

        for (const catName of uniqueCategories) {
            let cat = await Category.findOne({ name: catName });
            if (!cat) {
                cat = await Category.create({
                    name: catName,
                    img: { url: "https://via.placeholder.com/150", public_id: `cat_${catName.toLowerCase()}` }
                });
            }
            categoryMap[catName] = cat._id;
        }

        console.log("Categories ready");

        // Let's clear the previous MOCK products so there won't be duplicates
        await Product.deleteMany({ sku: { $regex: /^MOCK-/ } });

        for (const fp of frontendProducts) {
            const existing = await Product.findOne({ title: fp.name });
            if (existing) {
                console.log(`Product ${fp.name} already exists. Skipping.`);
                continue;
            }

            const newProduct = {
                title: fp.name,
                description: fp.description,
                shortDescription: fp.description.substring(0, 100),
                images: [{ url: fp.image, public_id: `img_${fp.id}` }],
                thumbnail: { url: fp.image, public_id: `thumb_${fp.id}` },
                brand: fp.brand,
                productCategory: categoryMap[fp.category],
                petType: fp.petType.toLowerCase(),
                category: fp.category.toLowerCase(),
                ageGroup: fp.ageGroup.toLowerCase(),
                size: fp.size.toLowerCase() === "all" ? "medium" : fp.size.toLowerCase(),
                price: fp.price,
                discountPrice: fp.subPrice,
                sku: `MOCK-${fp.id}-${Date.now().toString().slice(-4)}`,
                stock: 100,
                rating: fp.rating,
                reviewsCount: fp.reviews,
                tags: fp.tags
            };

            await Product.create(newProduct);
            console.log(`Inserted ${fp.name}`);
        }

        console.log(`Seeding complete with ${frontendProducts.length} products!`);
        process.exit(0);

    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedDB();
